version: '3'

services:
  mysql:
    container_name: mysqldb
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=finance_manager_db
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=student
      - MYSQL_ROOT_PASSWORD=root
  main-service:
    container_name: finance_manager
    build: ./
    volumes:
      - .m2:/root/.m2
      - ./:/FinanceManager
    ports:
      - "8081:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/finance_manager_db?allowPublicKeyRetrieval=true&useSSL=false",
              "spring.datasource.username" : "dev",
              "spring.datasource.password" : "student"
            }'
    depends_on:
      - mysql